# Generated by Django 5.0.2 on 2024-02-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('press_score', models.FloatField(max_length=2)),
                ('genres', models.CharField(max_length=255)),
                ('synopsis', models.TextField(max_length=1000)),
                ('date_de_sortie', models.IntegerField()),
                ('duree', models.IntegerField()),
                ('illustration_url', models.CharField(max_length=255)),
                ('genre_oeuvre', models.CharField(max_length=10)),
            ],
        ),
    ]
