# Generated by Django 5.0.2 on 2024-02-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='date_de_sortie',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='films',
            name='duree',
            field=models.CharField(max_length=4),
        ),
    ]
