# Generated by Django 5.0.2 on 2024-02-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_films_date_de_sortie_alter_films_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='date_de_sortie',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='films',
            name='duree',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='films',
            name='press_score',
            field=models.FloatField(default=0, max_length=2),
        ),
    ]
