# Generated by Django 5.0.2 on 2024-02-25 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('illustration', models.CharField(max_length=255, null=True)),
                ('vu', models.BooleanField(default=False)),
                ('mon_avis', models.TextField(max_length=300, null=True)),
                ('aime', models.BooleanField(default=False)),
                ('en_cours', models.BooleanField(default=False)),
                ('type', models.CharField(default='', max_length=255)),
                ('duree', models.IntegerField(default=0)),
                ('date_sortie', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
