# Generated by Django 5.0.2 on 2024-03-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='synopsis',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
