# Generated by Django 5.0.2 on 2024-03-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_watchlist_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='genres',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
