# Generated by Django 5.0.2 on 2024-03-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_watchlist_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='press_score',
            field=models.IntegerField(default=0),
        ),
    ]
