# Generated by Django 5.0.2 on 2024-06-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_watchlist_press_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='note_utilisateur',
            field=models.IntegerField(default=0),
        ),
    ]
