# Generated by Django 5.1.3 on 2024-11-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0005_watchlist_note_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='nbSaison',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='duree',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
