# Generated by Django 5.1.3 on 2024-11-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0006_watchlist_nbsaison_alter_watchlist_duree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='date_sortie',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
