# Generated by Django 5.1.3 on 2024-12-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0007_alter_watchlist_date_sortie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='press_score',
            new_name='user_score',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='acteurs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='realisateurs',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
