[phases.setup]
aptPkgs = ["default-libmysqlclient-dev", "pkg-config", "python3-dev", "build-essential", "gcc"]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn orq_api_auth.wsgi:application --bind 0.0.0.0:$PORT"